# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-10 22:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_ticket', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SubTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=200)),
                ('onboarding_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_services.ParentTicket')),
            ],
        ),
    ]
