# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-12-10 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subticket',
            name='tracking_status',
            field=models.CharField(choices=[('inqueue', 'In Queue'), ('pending', 'Pending'), ('onhold', 'On Hold'), ('complete', 'Complete')], default='inqueue', max_length=6),
        ),
    ]
